import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import ClientProviders from "./ClientProviders";

const cairo = Cairo({
  subsets: ["latin", "arabic"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairo.className} antialiased`}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
